theme: jekyll-theme-cayman
max_excerpt_chars: 167
paginate: 20
timezone: Asia/Shanghai
title: ARTS 记录

gitalk:
    enable: true
    owner: zhangao0086
    repo: zhangao0086.github.io
    clientID: 4f947d812cc002d38d52
    clientSecret: 7b39edb9c0c6ee98478c06ef994a093039e4caaa
    admin: zhangao0086
